/* Emits the two functions the whole Akeso relationship eventually runs on:
 *
 *   getBillingEntitlement(accountId)  — the app's one honest answer
 *   restoreBillingEntitlement(...)    — the one write Akeso may ever make
 *
 * Generated for the founder to read and commit — never installed silently.
 * The comments inside the generated code are part of the product: the founder
 * (or their coding agent) has to see WHY the six fields are separate, because
 * collapsing them back into one boolean is how the company-ending write
 * (restoring access to a banned account) becomes possible again.
 */

const SIX_FIELDS = `  // The six fields, and why they never collapse into one boolean:
  //   billingEntitled        — derived from Stripe. THE ONLY FIELD AKESO MAY CHANGE.
  //   manualComplimentaryAccess — a human gave free access on purpose. Not Akeso's.
  //   manualBillingOverride  — a human forced billing state on purpose. Not Akeso's.
  //   administrativeBlock    — an admin locked this account. Never overridden.
  //   securityOrAbuseBlock   — fraud/abuse lock. NEVER overridden, whatever Stripe says.
  //   finalAccessDecision    — what the app actually does. Read for reports, never written.`;

export function renderAdapter({ tableName = "profiles", accountColumn = "id", entitledColumn = "billing_entitled", language = "ts" } = {}) {
  const ts = language === "ts";
  return `// AKESO ADAPTER. Generated by Akeso Check. Read it, then commit it.
// Two functions. Nothing else. Akeso's entire access to this app goes through
// them, which means this file is also the complete list of what Akeso can do.

export const AKESO_ADAPTER_VERSION = "1";
export const AKESO_RULE_VERSION = "1"; // bump when your billing policy changes

${SIX_FIELDS}
export async function getBillingEntitlement(accountId${ts ? ": string" : ""}) {
  // TODO(you or your agent): replace this query with your real data source.
  // The Check found billing state around: table "${tableName}", column "${entitledColumn}".
  const row = await db
    .from("${tableName}")
    .select("${accountColumn}, ${entitledColumn}")
    .eq("${accountColumn}", accountId)
    .single();

  return {
    accountId,
    billingEntitled: Boolean(row?.${entitledColumn}),
    manualComplimentaryAccess: false, // wire to your comp flag if one exists
    manualBillingOverride: false,
    administrativeBlock: false,       // wire to your admin-lock flag if one exists
    securityOrAbuseBlock: false,      // wire to your abuse-lock flag if one exists
    finalAccessDecision: Boolean(row?.${entitledColumn}), // what your gates actually use
    ruleVersion: AKESO_RULE_VERSION,
    adapterVersion: AKESO_ADAPTER_VERSION,
    decisionSource: "${tableName}.${entitledColumn}",
    readAt: new Date().toISOString(),
  };
}

// The one write. Changes billingEntitled and NOTHING else, and only when the
// row still looks the way the caller last saw it (compare-and-set) — a restore
// racing a newer change must lose, loudly, not win, silently.
export async function restoreBillingEntitlement(
  accountId${ts ? ": string" : ""},
  expectedCurrentState${ts ? ": { billingEntitled: boolean }" : ""},
  targetState${ts ? ": { billingEntitled: boolean }" : ""},
  ruleVersion${ts ? ": string" : ""},
  idempotencyKey${ts ? ": string" : ""},
  reasonCode${ts ? ": string" : ""},
) {
  if (ruleVersion !== AKESO_RULE_VERSION) {
    return { result: "conflict"${ts ? " as const" : ""}, reason: "rule version changed since this restore was prepared" };
  }

  const before = await getBillingEntitlement(accountId);

  // Blocks are load-bearing. A blocked account is never restored by billing
  // logic, whatever Stripe says — this is the line between a billing tool and
  // an incident.
  if (before.administrativeBlock || before.securityOrAbuseBlock) {
    return { result: "unsupported"${ts ? " as const" : ""}, reason: "account carries an administrative or security block", before };
  }
  if (before.billingEntitled === targetState.billingEntitled) {
    return { result: "no_op"${ts ? " as const" : ""}, before };
  }
  if (before.billingEntitled !== expectedCurrentState.billingEntitled) {
    return { result: "conflict"${ts ? " as const" : ""}, reason: "state changed since it was read", before };
  }

  // TODO(you or your agent): the actual compare-and-set update, e.g.
  //   UPDATE ${tableName} SET ${entitledColumn} = $target
  //   WHERE ${accountColumn} = $accountId AND ${entitledColumn} = $expected
  // and record { idempotencyKey, reasonCode, before, after } in an audit table.
  const updated = await db
    .from("${tableName}")
    .update({ ${entitledColumn}: targetState.billingEntitled })
    .eq("${accountColumn}", accountId)
    .eq("${entitledColumn}", expectedCurrentState.billingEntitled)
    .select();

  const after = await getBillingEntitlement(accountId);
  const applied = after.billingEntitled === targetState.billingEntitled;
  return {
    result: applied ? ${ts ? '"applied" as const' : '"applied"'} : ${ts ? '"failed" as const' : '"failed"'},
    idempotencyKey,
    reasonCode,
    before,
    after,
    verified: applied, // success is claimed only after the re-read agrees
  };
}
`;
}

/* A runnable reference implementation of the same contract against a plain
   JSON store — what the fixtures use, and what the generated code's tests can
   exercise so the contract itself is proven even before a founder wires it. */
export function renderReferenceAdapter() {
  return renderAdapter({ language: "mjs" })
    .replace(/const row = await db[\s\S]*?\.single\(\);/,
      `const store = JSON.parse(await (await import("node:fs/promises")).readFile(process.env.AKESO_REF_DB, "utf8"));
  const row = store[accountId] || null;`)
    .replace(/const updated = await db[\s\S]*?\.select\(\);/,
      `const fs = await import("node:fs/promises");
  const store = JSON.parse(await fs.readFile(process.env.AKESO_REF_DB, "utf8"));
  if (store[accountId] && Boolean(store[accountId].billing_entitled) === expectedCurrentState.billingEntitled) {
    store[accountId].billing_entitled = targetState.billingEntitled;
    await fs.writeFile(process.env.AKESO_REF_DB, JSON.stringify(store));
  }`)
    .replace(/Boolean\(row\?\.billing_entitled\)/g, "Boolean(row?.billing_entitled)")
    .replace(/administrativeBlock: false,.*$/m, "administrativeBlock: Boolean(row?.admin_block),")
    .replace(/securityOrAbuseBlock: false,.*$/m, "securityOrAbuseBlock: Boolean(row?.abuse_block),");
}
