import { createHash } from "node:crypto";
import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

/* The Fix: turns what the Check found into working code, applies it only when
 * the founder says so, and can always put it back.
 *
 * Shape of the repair, and why it is this shape:
 *
 *   akeso/entitlement.*   ONE file holds every line that touches this app's
 *                         database. Everything else generated here is app-
 *                         agnostic and correct as written, so there is exactly
 *                         one place a founder (or their agent) can get wrong.
 *   the webhook handler   raw-body signature check, all seven events,
 *                         idempotent by event id, ordered by event created,
 *                         entitlement derived from subscription status.
 *   akeso/reconcile.*     the backstop: re-derives entitlement from Stripe
 *                         itself, because webhooks are missable by design.
 *   akeso/migration.sql   the idempotency and ordering tables. DDL is never
 *                         run by us; the founder pastes it.
 *
 * Safety, in the order it matters. Nothing here is applied without --apply.
 * Nothing is overwritten without a backup. A dirty git tree stops the run,
 * because "I can just undo it" has to be true. Every generated file carries a
 * marker, and revert refuses to touch a file that lost its marker (that means
 * a human edited it, and their work outranks ours).
 */

/* The Go toolchain's convention, because tools and humans both already know
   it: a generated file says so on its first line. */
export const AKESO_MARKER = "Code generated by Akeso. DO NOT EDIT.";
const BACKUP_ROOT = path.join(".akeso", "backups");

/* ---------------------------------------------------------------- planning */

/* What is actually broken, in the founder's words, each tied to the evidence
   that justifies it. A repair with no evidence behind it never appears. */
export function planRepairs({ detection, lifecycle = null, sandbox = null }) {
  const handler = detection.webhookHandlers?.[0] || null;
  const repairs = [];

  if (!handler) {
    repairs.push({
      id: "no-handler",
      title: "Your app has nowhere for Stripe to deliver payment events",
      because: "No Stripe webhook handler was found anywhere in the project.",
      severity: "critical",
    });
  } else {
    if (!handler.verifiesSignature) {
      repairs.push({
        id: "verify-signature",
        title: "Check Stripe's signature before trusting an event",
        because: `${handler.file} accepts events without verifying Stripe's signature, so anyone who finds the URL can forge them.`,
        severity: "critical",
      });
    } else if (!handler.rawBodySeen) {
      repairs.push({
        id: "raw-body",
        title: "Verify the signature against the raw request body",
        because: `${handler.file} verifies a signature, but the raw body was not seen. Verification against a re-serialized body fails at runtime.`,
        severity: "high",
      });
    }
    if (handler.missingEvents?.length) {
      repairs.push({
        id: "handle-all-events",
        title: "Handle every event that changes who is paying",
        because: `${handler.file} ignores ${handler.missingEvents.length} of the 7 lifecycle events: ${handler.missingEvents.join(", ")}.`,
        severity: handler.missingEvents.some((event) => event.includes("deleted") || event.includes("updated")) ? "critical" : "high",
      });
    }
  }

  /* Executed evidence outranks read evidence: a scenario that actually failed
     names its own repair, whichever driver saw it. */
  const failed = [
    ...(lifecycle?.results || []).filter((result) => result.outcome === "fail"),
    ...(sandbox?.phases || []).filter((phase) => phase.outcome === "fail").map((phase) => ({ id: phase.phase, name: phase.phase, expected: phase.expected })),
  ];
  const failedRemoval = failed.filter((result) => result.expected === false);
  const failedGrant = failed.filter((result) => result.expected === true);

  if (failedRemoval.length) {
    repairs.push({
      id: "removals-must-remove",
      title: "End paid access when the customer stops paying",
      because: `Tested against your running app: ${failedRemoval.map((r) => `"${r.name}"`).join(", ")} left access switched on. This is the failure that leaks money every day.`,
      severity: "critical",
    });
  }
  if (failedGrant.length) {
    repairs.push({
      id: "grants-must-grant",
      title: "Give paid access when the customer pays",
      because: `Tested against your running app: ${failedGrant.map((r) => `"${r.name}"`).join(", ")} left a paying customer locked out.`,
      severity: "critical",
    });
  }

  const idempotency = (lifecycle?.results || []).find((result) => result.id === "duplicate-delivery" && result.outcome === "fail");
  const ordering = (lifecycle?.results || []).find((result) => result.id === "out-of-order" && result.outcome === "fail");
  if (idempotency) {
    repairs.push({ id: "idempotency", title: "Apply the same event only once", because: "Stripe delivered the same event twice and your app changed state both times.", severity: "high" });
  }
  if (ordering) {
    repairs.push({ id: "ordering", title: "Ignore events that arrive late and out of order", because: "An older 'still active' event arrived after a cancellation and switched access back on.", severity: "high" });
  }

  const clientGate = (detection.accessDecisionSites || []).find((site) => site.clientSideOnly);
  if (clientGate) {
    repairs.push({
      id: "client-side-gate",
      title: "Decide paid access on the server, not in the browser",
      because: `${clientGate.file} decides paid access in browser code, which anyone can step around with devtools. The generated entitlement function belongs on the server; this one has to be moved by hand.`,
      severity: "high",
      handWork: true,
    });
  }

  return repairs;
}

/* ------------------------------------------------------------- code output */

/* TypeScript is a property of the project (does it have a tsconfig?), never of
   the framework. Writing .ts into a plain JavaScript app produces a file that
   cannot load, and that mistake is invisible until runtime. */
const ts = (detection) => Boolean(detection.framework?.typescript);

function entitlementModule(detection) {
  const typed = ts(detection);
  const t = (annotation) => (typed ? annotation : "");
  const supabase = detection.database?.kind === "supabase";
  const table = detection.database?.entitlementTable || "profiles";
  const column = detection.database?.entitlementColumn || "billing_entitled";

  /* Where the table and column came from is stated in the file itself. Code
     generated from a default must never look like code generated from
     evidence — that is how a founder ends up debugging a query against a
     table their app does not have. */
  const provenance = detection.database?.tableConfirmed && detection.database?.columnConfirmed
    ? `// Your schema, as found in your code: table "${table}", column "${column}".`
    : `// HEADS UP: the Check could NOT confirm ${!detection.database?.tableConfirmed ? `the table${!detection.database?.columnConfirmed ? " or the column" : ""}` : "the column"} from your code,
// so this uses the common default: table "${table}", column "${column}".
// Check these two names against your database before trusting this file.`;

  const header = `// ${AKESO_MARKER}
// Akeso: the only file here that touches your database.
//
// Everything else Akeso generated is correct as written. If something needs
// adjusting to fit your schema, it is in this file and nowhere else.
//
${provenance}
//
// The six fields never collapse into one boolean:
//   billingEntitled           derived from Stripe. THE ONLY FIELD AKESO CHANGES.
//   manualComplimentaryAccess a human gave free access on purpose. Not ours.
//   manualBillingOverride     a human forced billing state on purpose. Not ours.
//   administrativeBlock       an admin locked the account. Never overridden.
//   securityOrAbuseBlock      fraud or abuse lock. NEVER overridden, whatever Stripe says.
//   finalAccessDecision       what your gates actually do. Read, never written.
`;

  if (supabase) {
    return `${header}
import { createClient } from "@supabase/supabase-js";

const db = createClient(
  process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL${typed ? "!" : ""},
  process.env.SUPABASE_SERVICE_ROLE_KEY${typed ? "!" : ""},
);

export const AKESO_RULE_VERSION = "1";

// Which Stripe subscription statuses mean "entitled" under your policy.
// past_due is the grace period: still entitled. Change this line to change
// the policy, and bump AKESO_RULE_VERSION when you do.
const ENTITLED_STATUSES = new Set(["active", "trialing", "past_due"]);
export const entitledByStatus = (status${t(": string")}) => ENTITLED_STATUSES.has(status);

export async function getBillingEntitlement(accountId${t(": string")}) {
  const { data, error } = await db
    .from("${table}")
    .select("*")
    .eq("id", accountId)
    .maybeSingle();

  // A read error is never reported as "not entitled". Guessing "false" here
  // once cost a whole session a wrong conclusion, and would lock out a paying
  // customer in production.
  if (error) throw new Error(\`entitlement read failed: \${error.message}\`);

  return {
    accountId,
    billingEntitled: Boolean(data?.${column}),
    manualComplimentaryAccess: Boolean(data?.complimentary_access),
    manualBillingOverride: Boolean(data?.billing_override),
    administrativeBlock: Boolean(data?.admin_block),
    securityOrAbuseBlock: Boolean(data?.abuse_block),
    finalAccessDecision: Boolean(data?.${column}),
    ruleVersion: AKESO_RULE_VERSION,
    decisionSource: "${table}.${column}",
    readAt: new Date().toISOString(),
    exists: Boolean(data),
  };
}

// The one write. Changes ${column} and nothing else, and only if the row still
// looks the way we last read it, so a restore racing a newer change loses
// loudly instead of winning silently.
export async function applyBillingEntitlement(
  accountId${t(": string")},
  target${t(": boolean")},
  { expected, reasonCode, idempotencyKey }${t(": { expected: boolean | null; reasonCode: string; idempotencyKey: string }")},
) {
  const before = await getBillingEntitlement(accountId);
  if (!before.exists) return { result: "unsupported"${typed ? " as const" : ""}, reason: "no such account", before };
  if (before.administrativeBlock || before.securityOrAbuseBlock) {
    return { result: "unsupported"${typed ? " as const" : ""}, reason: "account carries an administrative or security block", before };
  }
  if (before.manualComplimentaryAccess || before.manualBillingOverride) {
    return { result: "unsupported"${typed ? " as const" : ""}, reason: "a human set this account's access on purpose", before };
  }
  if (before.billingEntitled === target) return { result: "no_op"${typed ? " as const" : ""}, before };
  if (expected !== null && before.billingEntitled !== expected) {
    return { result: "conflict"${typed ? " as const" : ""}, reason: "state changed since it was read", before };
  }

  const { error } = await db
    .from("${table}")
    .update({ ${column}: target })
    .eq("id", accountId)
    .eq("${column}", before.billingEntitled);
  if (error) return { result: "failed"${typed ? " as const" : ""}, reason: error.message, before };

  const after = await getBillingEntitlement(accountId);
  return {
    result: after.billingEntitled === target ? ${typed ? '"applied" as const' : '"applied"'} : ${typed ? '"failed" as const' : '"failed"'},
    idempotencyKey, reasonCode, before, after,
    verified: after.billingEntitled === target, // success is claimed only after the re-read agrees
  };
}

// Idempotency and ordering, both keyed per account. Requires the tables in
// akeso/migration.sql.
export async function alreadyProcessed(eventId${t(": string")}) {
  const { data } = await db.from("akeso_processed_events").select("event_id").eq("event_id", eventId).maybeSingle();
  return Boolean(data);
}

export async function markProcessed(eventId${t(": string")}, eventType${t(": string")}) {
  await db.from("akeso_processed_events").insert({ event_id: eventId, event_type: eventType });
}

export async function lastEventCreated(accountId${t(": string")}) {
  const { data } = await db.from("akeso_event_watermarks").select("last_event_created").eq("account_id", accountId).maybeSingle();
  return data?.last_event_created ?? 0;
}

export async function setLastEventCreated(accountId${t(": string")}, created${t(": number")}) {
  await db.from("akeso_event_watermarks").upsert({ account_id: accountId, last_event_created: created });
}

export async function allAccountEntitlements() {
  const { data, error } = await db.from("${table}").select("id, ${column}");
  if (error) throw new Error(\`entitlement list failed: \${error.message}\`);
  return (data || []).map((row${t(": any")}) => ({ account: row.id, billingEntitled: Boolean(row.${column}) }));
}
`;
  }

  return `${header}
// Your database was not one Akeso generates finished code for, so these are
// stubs with the contract spelled out. Fill in the six marked queries (or hand
// this file to your coding agent) and nothing else needs touching.

export const AKESO_RULE_VERSION = "1";

const ENTITLED_STATUSES = new Set(["active", "trialing", "past_due"]);
export const entitledByStatus = (status${t(": string")}) => ENTITLED_STATUSES.has(status);

export async function getBillingEntitlement(accountId${t(": string")}) {
  // TODO(1): read the account row. THROW on a read error, never return false —
  // returning false here locks out paying customers.
  const row${t(": any")} = await yourDatabase.findAccount(accountId);

  return {
    accountId,
    billingEntitled: Boolean(row?.${column}),
    manualComplimentaryAccess: Boolean(row?.complimentary_access),
    manualBillingOverride: Boolean(row?.billing_override),
    administrativeBlock: Boolean(row?.admin_block),
    securityOrAbuseBlock: Boolean(row?.abuse_block),
    finalAccessDecision: Boolean(row?.${column}),
    ruleVersion: AKESO_RULE_VERSION,
    decisionSource: "${table}.${column}",
    readAt: new Date().toISOString(),
    exists: Boolean(row),
  };
}

export async function applyBillingEntitlement(
  accountId${t(": string")},
  target${t(": boolean")},
  { expected, reasonCode, idempotencyKey }${t(": { expected: boolean | null; reasonCode: string; idempotencyKey: string }")},
) {
  const before = await getBillingEntitlement(accountId);
  if (!before.exists) return { result: "unsupported"${typed ? " as const" : ""}, reason: "no such account", before };
  if (before.administrativeBlock || before.securityOrAbuseBlock) {
    return { result: "unsupported"${typed ? " as const" : ""}, reason: "account carries an administrative or security block", before };
  }
  if (before.manualComplimentaryAccess || before.manualBillingOverride) {
    return { result: "unsupported"${typed ? " as const" : ""}, reason: "a human set this account's access on purpose", before };
  }
  if (before.billingEntitled === target) return { result: "no_op"${typed ? " as const" : ""}, before };
  if (expected !== null && before.billingEntitled !== expected) {
    return { result: "conflict"${typed ? " as const" : ""}, reason: "state changed since it was read", before };
  }

  // TODO(2): compare-and-set. The WHERE clause must include the current value,
  // so a concurrent change makes this update match zero rows instead of racing.
  await yourDatabase.updateAccountIf(accountId, { ${column}: target }, { ${column}: before.billingEntitled });

  const after = await getBillingEntitlement(accountId);
  return {
    result: after.billingEntitled === target ? ${typed ? '"applied" as const' : '"applied"'} : ${typed ? '"failed" as const' : '"failed"'},
    idempotencyKey, reasonCode, before, after,
    verified: after.billingEntitled === target,
  };
}

export async function alreadyProcessed(eventId${t(": string")}) {
  return Boolean(await yourDatabase.findProcessedEvent(eventId)); // TODO(3)
}
export async function markProcessed(eventId${t(": string")}, eventType${t(": string")}) {
  await yourDatabase.insertProcessedEvent({ event_id: eventId, event_type: eventType }); // TODO(4)
}
export async function lastEventCreated(accountId${t(": string")}) {
  return (await yourDatabase.findWatermark(accountId))?.last_event_created ?? 0; // TODO(5)
}
export async function setLastEventCreated(accountId${t(": string")}, created${t(": number")}) {
  await yourDatabase.upsertWatermark({ account_id: accountId, last_event_created: created }); // TODO(6)
}
export async function allAccountEntitlements() {
  const rows${t(": any[]")} = await yourDatabase.allAccounts(); // TODO(7), used by reconcile
  return rows.map((row) => ({ account: row.id, billingEntitled: Boolean(row.${column}) }));
}
`;
}

/* The seven events, and what each one means for entitlement. This table is the
   heart of the repair and is identical for every app, which is exactly why it
   belongs in generated code and not in a founder's head. */
const EVENT_LOGIC = `  switch (event.type) {
    case "checkout.session.completed":
      // A completed checkout means paid, unless the session says otherwise.
      target = object.payment_status ? object.payment_status === "paid" : true;
      break;
    case "invoice.paid":
      target = true;
      break;
    case "invoice.payment_failed":
      // Not a removal on its own. Stripe retries; the subscription status
      // events below carry the real decision.
      target = null;
      break;
    case "customer.subscription.created":
    case "customer.subscription.updated":
      target = entitledByStatus(object.status);
      break;
    case "customer.subscription.deleted":
      target = false;
      break;
    case "charge.refunded":
      // Your policy. Default: a refund ends access. Change this one line if
      // your policy differs, and bump AKESO_RULE_VERSION.
      target = false;
      break;
    default:
      target = null;
  }`;

const HANDLER_BODY = (typed) => `const ENTITLEMENT_EVENTS = new Set([
  "checkout.session.completed",
  "invoice.paid",
  "invoice.payment_failed",
  "customer.subscription.created",
  "customer.subscription.updated",
  "customer.subscription.deleted",
  "charge.refunded",
]);

// Which account an event is about. Stripe carries it in different places
// depending on how the subscription was made, so all three are checked.
function accountOf(object${typed ? ": any" : ""}) {
  return object.client_reference_id || object.metadata?.account || object.metadata?.account_id || object.customer || null;
}

export async function applyStripeEvent(event${typed ? ": any" : ""}) {
  if (!ENTITLEMENT_EVENTS.has(event.type)) return { handled: false, reason: "not an entitlement event" };

  // Idempotency: Stripe retries for up to three days and can deliver the same
  // event more than once. Applying it twice must be impossible.
  if (await alreadyProcessed(event.id)) return { handled: false, reason: "already processed" };

  const object = event.data.object;
  const account = accountOf(object);
  if (!account) return { handled: false, reason: "no account on this event" };

  let target${typed ? ": boolean | null" : ""} = null;
${EVENT_LOGIC}

  if (target === null) {
    await markProcessed(event.id, event.type);
    return { handled: false, reason: "no entitlement change for this event" };
  }

  // Ordering: Stripe does not guarantee delivery order. An older event that
  // arrives late must never overwrite a newer decision.
  const watermark = await lastEventCreated(account);
  if (event.created < watermark) {
    await markProcessed(event.id, event.type);
    return { handled: false, reason: "older than the last event applied to this account" };
  }

  const outcome = await applyBillingEntitlement(account, target, {
    expected: null,
    reasonCode: \`stripe:\${event.type}\`,
    idempotencyKey: event.id,
  });

  await setLastEventCreated(account, event.created);
  await markProcessed(event.id, event.type);
  return { handled: true, account, target, outcome };
}`;

function webhookHandler(detection, entitlementImport) {
  const framework = detection.framework?.framework || "node-other";
  const typed = ts(detection);
  const from = entitlementImport || "@/akeso/entitlement";
  const head = `// ${AKESO_MARKER}
// Akeso: Stripe webhook handler.
//
// Correct as written. Every line that touches your database lives in
// ./entitlement, so this file should not need editing.
//
// What it does, in order: verify Stripe's signature against the RAW body,
// ignore events already applied, ignore events older than the last one applied
// to that account, derive entitlement from subscription status, and write
// through the one guarded function.
`;

  if (framework === "next-app-router") {
    return `${head}
import Stripe from "stripe";
import {
  alreadyProcessed, applyBillingEntitlement, entitledByStatus,
  lastEventCreated, markProcessed, setLastEventCreated,
} from "${from}";

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY${typed ? "!" : ""});

${HANDLER_BODY(typed)}

export async function POST(request${typed ? ": Request" : ""}) {
  // The raw body, unparsed. Verification against a re-serialized body fails.
  const rawBody = await request.text();
  const signature = request.headers.get("stripe-signature");

  let event${typed ? ": Stripe.Event" : ""};
  try {
    event = stripe.webhooks.constructEvent(rawBody, signature${typed ? "!" : ""}, process.env.STRIPE_WEBHOOK_SECRET${typed ? "!" : ""});
  } catch (error${typed ? ": any" : ""}) {
    // An unverified event is not a Stripe event. 400, and nothing else happens.
    return new Response(\`signature verification failed: \${error.message}\`, { status: 400 });
  }

  try {
    const result = await applyStripeEvent(event);
    return Response.json({ received: true, ...result });
  } catch (error${typed ? ": any" : ""}) {
    // 500 tells Stripe to retry. Swallowing the error here would silently drop
    // a real billing change forever.
    return new Response(\`handler failed: \${error.message}\`, { status: 500 });
  }
}
`;
  }

  if (framework === "next-pages") {
    return `${head}
import Stripe from "stripe";
import {
  alreadyProcessed, applyBillingEntitlement, entitledByStatus,
  lastEventCreated, markProcessed, setLastEventCreated,
} from "${from}";

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY${typed ? "!" : ""});

// Next's body parser must be off, or the raw body is gone before we see it.
export const config = { api: { bodyParser: false } };

${HANDLER_BODY(typed)}

async function readRawBody(request${typed ? ": any" : ""}) {
  const chunks${typed ? ": Buffer[]" : ""} = [];
  for await (const chunk of request) chunks.push(typeof chunk === "string" ? Buffer.from(chunk) : chunk);
  return Buffer.concat(chunks);
}

export default async function handler(request${typed ? ": any" : ""}, response${typed ? ": any" : ""}) {
  if (request.method !== "POST") return response.status(405).end();

  const rawBody = await readRawBody(request);
  let event${typed ? ": Stripe.Event" : ""};
  try {
    event = stripe.webhooks.constructEvent(rawBody, request.headers["stripe-signature"], process.env.STRIPE_WEBHOOK_SECRET${typed ? "!" : ""});
  } catch (error${typed ? ": any" : ""}) {
    return response.status(400).send(\`signature verification failed: \${error.message}\`);
  }

  try {
    const result = await applyStripeEvent(event);
    return response.json({ received: true, ...result });
  } catch (error${typed ? ": any" : ""}) {
    return response.status(500).send(\`handler failed: \${error.message}\`);
  }
}
`;
  }

  return `${head}
const Stripe = require("stripe");
const {
  alreadyProcessed, applyBillingEntitlement, entitledByStatus,
  lastEventCreated, markProcessed, setLastEventCreated,
} = require("./entitlement");

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);

${HANDLER_BODY(false)}

// Mount with the RAW body parser, before any express.json():
//   app.post("/api/stripe/webhook", express.raw({ type: "application/json" }), akesoWebhook);
async function akesoWebhook(request, response) {
  let event;
  try {
    event = stripe.webhooks.constructEvent(request.body, request.headers["stripe-signature"], process.env.STRIPE_WEBHOOK_SECRET);
  } catch (error) {
    return response.status(400).send(\`signature verification failed: \${error.message}\`);
  }

  try {
    const result = await applyStripeEvent(event);
    return response.json({ received: true, ...result });
  } catch (error) {
    return response.status(500).send(\`handler failed: \${error.message}\`);
  }
}

module.exports = { akesoWebhook, applyStripeEvent };
`;
}

/* The backstop. Webhooks get missed: endpoints go down, deploys drop events,
   Stripe gives up after three days of retries. This re-derives the truth from
   Stripe itself, which is the only source that cannot drift. */
function reconcileJob(detection) {
  const typed = ts(detection);
  const isModule = detection.framework?.framework?.startsWith("next") || detection.framework?.framework === "node-other";
  const imports = isModule
    ? `import Stripe from "stripe";
import { allAccountEntitlements, applyBillingEntitlement, entitledByStatus, getBillingEntitlement } from "./entitlement";`
    : `const Stripe = require("stripe");
const { allAccountEntitlements, applyBillingEntitlement, entitledByStatus, getBillingEntitlement } = require("./entitlement");`;

  return `// ${AKESO_MARKER}
// Akeso: reconciliation backstop. Run it on a schedule (nightly is fine).
//
// Webhooks get missed. Endpoints go down mid-deploy, Stripe stops retrying
// after three days, and events can arrive out of order. This job does not
// trust events at all: it asks Stripe what is true now, compares that to what
// your app believes, and reports every disagreement.
//
// It is READ-ONLY by default. Pass { apply: true } to also correct
// disagreements, and even then it only ever grants access instantly; removals
// are listed for you to approve, because a wrong removal locks out a paying
// customer.
${imports}

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY${typed ? "!" : ""});

export async function reconcile({ apply = false, removeToo = false } = {}) {
  const stripeSide = new Map();
  for await (const sub of stripe.subscriptions.list({ status: "all", limit: 100, expand: ["data.items.data.price"] })) {
    const account = sub.metadata?.account || sub.metadata?.account_id || sub.customer;
    const entitled = entitledByStatus(sub.status);
    // One account can have several subscriptions; any paying one entitles it.
    stripeSide.set(String(account), (stripeSide.get(String(account)) || false) || entitled);
  }

  const appSide = await allAccountEntitlements();
  const shouldGrant = [];
  const shouldRemove = [];

  for (const row of appSide) {
    const stripeSays = stripeSide.get(String(row.account));
    if (stripeSays === undefined) continue; // no subscription at all: reported, never assumed
    if (stripeSays && !row.billingEntitled) shouldGrant.push(row.account);
    if (!stripeSays && row.billingEntitled) shouldRemove.push(row.account);
  }

  const applied = [];
  if (apply) {
    for (const account of shouldGrant) {
      applied.push({ account, direction: "grant", ...await applyBillingEntitlement(account, true, { expected: false, reasonCode: "reconcile:grant", idempotencyKey: \`reconcile-grant-\${account}-\${new Date().toISOString().slice(0, 10)}\` }) });
    }
    if (removeToo) {
      for (const account of shouldRemove) {
        applied.push({ account, direction: "remove", ...await applyBillingEntitlement(account, false, { expected: true, reasonCode: "reconcile:remove", idempotencyKey: \`reconcile-remove-\${account}-\${new Date().toISOString().slice(0, 10)}\` }) });
      }
    }
  }

  return {
    checked: appSide.length,
    shouldGrant,
    shouldRemove,
    applied,
    clean: shouldGrant.length === 0 && shouldRemove.length === 0,
    at: new Date().toISOString(),
  };
}
`;
}

/* The two endpoints Akeso talks to, generated into the customer's own app.
 *
 * This is the whole surface of what Akeso can do to an app, which is why it is
 * generated code the founder reads and commits rather than a database
 * connection they hand over. Deleting these two files removes Akeso's access
 * completely, and that has to stay true.
 *
 * Both refuse everything that is not signed with a shared secret the founder
 * generates, and the restore endpoint additionally goes through the app's own
 * guarded entitlement function, so blocks and human overrides still win.
 */
function akesoEndpoints(detection, importFrom) {
  const typed = ts(detection);
  const t = (annotation) => (typed ? annotation : "");
  const framework = detection.framework?.framework || "node-other";
  const nextish = framework.startsWith("next");
  /* Each generated file computes its OWN specifier for the modules it imports.
     Reusing the webhook handler's specifier worked only by accident when the
     two files happened to sit at the same depth, and produced an import of a
     name the target module does not export as soon as they did not. */
  const routeDir = nextish ? "app/api/akeso" : "akeso";
  const routePath = (name) => (nextish
    ? path.join(routeDir, name, "route.x")
    : path.join(routeDir, `${name}.x`));
  const entitlementFrom = (name) => importFrom(routePath(name), "entitlement");
  const verifyFrom = (name) => importFrom(routePath(name), "verify");

  const verifier = `// ${AKESO_MARKER}
// Akeso: shared-secret verification for the two Akeso endpoints.
//
// Same signing scheme Stripe uses, for the same reason: a timestamp inside the
// signed material, so a captured request cannot be replayed later.
import { createHmac, timingSafeEqual } from "node:crypto";

const SECRET = process.env.AKESO_SHARED_SECRET;
const TOLERANCE_SECONDS = 300;

export function verifyAkesoRequest(rawBody${t(": string")}, header${t(": string | null")}) {
  if (!SECRET) return { valid: false, reason: "AKESO_SHARED_SECRET is not set in this app" };
  if (!header) return { valid: false, reason: "no signature" };

  const parts = Object.fromEntries(String(header).split(",").map((part) => part.split("=")));
  if (!parts.t || !parts.v1) return { valid: false, reason: "malformed signature" };

  const age = Math.abs(Math.floor(Date.now() / 1000) - Number(parts.t));
  if (!Number.isFinite(age) || age > TOLERANCE_SECONDS) return { valid: false, reason: "signature too old" };

  const expected = createHmac("sha256", SECRET).update(\`\${parts.t}.\${rawBody}\`).digest("hex");
  try {
    if (!timingSafeEqual(Buffer.from(expected, "hex"), Buffer.from(parts.v1, "hex"))) {
      return { valid: false, reason: "signature does not match" };
    }
  } catch { return { valid: false, reason: "signature does not match" }; }

  return { valid: true };
}
`;

  /* The write endpoint. Everything dangerous about Akeso passes through here,
     so it is deliberately small enough to read in one sitting. */
  const restore = `// ${AKESO_MARKER}
// Akeso: the ONLY way Akeso can change anything in this app.
//
// Read this file. It is the complete list of what Akeso is able to do:
// set one boolean, on one account, through your own guarded function, and only
// when the row still looks the way Akeso last read it.
//
// Delete this file and Akeso can no longer write to your app at all.
import { applyBillingEntitlement, AKESO_RULE_VERSION } from "${entitlementFrom("restore")}";
import { verifyAkesoRequest } from "${verifyFrom("restore")}";

export async function POST(request${t(": Request")}) {
  const rawBody = await request.text();
  const check = verifyAkesoRequest(rawBody, request.headers.get("akeso-signature"));
  if (!check.valid) return new Response(check.reason, { status: 401 });

  let body${t(": any")};
  try { body = JSON.parse(rawBody); } catch { return new Response("bad json", { status: 400 }); }

  const { account, target, expectedState, reasonCode, idempotencyKey, ruleVersion, dryRun } = body;
  if (typeof account !== "string" || typeof target !== "boolean") {
    return new Response("account and target are required", { status: 400 });
  }

  // The rule version is part of the contract: if your billing policy changed
  // since Akeso prepared this restore, the restore is stale and must not run.
  if (ruleVersion && ruleVersion !== AKESO_RULE_VERSION) {
    return Response.json({ result: "conflict", reason: "your billing rules changed since this was prepared" });
  }

  // A dry run reports what would happen and changes nothing. Akeso treats an
  // "applied" answer to a dry run as a protocol violation, so never do work here.
  if (dryRun) {
    return Response.json({ result: "dry_run", wouldTarget: target, account });
  }

  try {
    const outcome = await applyBillingEntitlement(account, target, {
      expected: typeof expectedState === "boolean" ? expectedState : null,
      reasonCode: reasonCode || "akeso:restore",
      idempotencyKey: idempotencyKey || \`akeso-\${account}-\${Date.now()}\`,
    });
    return Response.json({
      ...outcome,
      // Akeso does not take this endpoint's word for success either: it re-reads.
      // Reporting verified truthfully is what makes that check meaningful.
      verified: Boolean(outcome.verified),
      after: outcome.after ? { billingEntitled: outcome.after.billingEntitled } : null,
      before: outcome.before ? { billingEntitled: outcome.before.billingEntitled } : null,
    });
  } catch (error${t(": any")}) {
    return Response.json({ result: "failed", reason: error.message }, { status: 500 });
  }
}
`;

  /* The read endpoint. Monitor needs the app's own answer for every account;
     without it the comparison has only one side. */
  const entitlements = `// ${AKESO_MARKER}
// Akeso: the read side. Returns this app's own answer to "who currently has
// paid access", so it can be compared against Stripe.
//
// Signed like the restore endpoint, because an unauthenticated list of who is
// paying you is a data leak, not a convenience.
import { allAccountEntitlements } from "${entitlementFrom("entitlements")}";
import { verifyAkesoRequest } from "${verifyFrom("entitlements")}";

export async function POST(request${t(": Request")}) {
  const rawBody = await request.text();
  const check = verifyAkesoRequest(rawBody, request.headers.get("akeso-signature"));
  if (!check.valid) return new Response(check.reason, { status: 401 });

  try {
    const accounts = await allAccountEntitlements();
    return Response.json({ accounts, readAt: new Date().toISOString() });
  } catch (error${t(": any")}) {
    // A failed read is reported as a failure, never as an empty list. An empty
    // list would read as "nobody has access" and could trigger mass grants.
    return Response.json({ error: error.message }, { status: 500 });
  }
}
`;

  return { verifier, restore, entitlements, nextish };
}

function migrationSql(detection) {
  const column = detection.database?.entitlementColumn || "billing_entitled";
  const table = detection.database?.entitlementTable || "profiles";
  return `-- ${AKESO_MARKER} — paste this into your database's SQL editor.
-- Akeso never runs schema changes for you. Read it first; it only adds.

-- Every Stripe event id we have already applied, so a repeat delivery is a
-- no-op instead of a second state change.
create table if not exists akeso_processed_events (
  event_id   text primary key,
  event_type text not null,
  applied_at timestamptz not null default now()
);

-- The newest event already applied per account, so a late event that Stripe
-- delivers out of order cannot overwrite a newer decision.
create table if not exists akeso_event_watermarks (
  account_id         text primary key,
  last_event_created bigint not null,
  updated_at         timestamptz not null default now()
);

-- Optional but recommended: the fields that keep a billing fix from becoming
-- an incident. Without them, a restore cannot tell a banned account from an
-- unpaid one. Akeso refuses to write to an account carrying either block.
alter table ${table} add column if not exists complimentary_access boolean not null default false;
alter table ${table} add column if not exists billing_override     boolean not null default false;
alter table ${table} add column if not exists admin_block          boolean not null default false;
alter table ${table} add column if not exists abuse_block          boolean not null default false;

-- The entitlement column itself, if the Check did not find one.
alter table ${table} add column if not exists ${column} boolean not null default false;
`;
}

/* Every file the repair would write, with its reason. Pure: builds the plan
   without touching the disk, so the dry run and the apply cannot disagree. */
export function buildFixPlan({ detection, lifecycle = null, sandbox = null, withEndpoints = false }) {
  const repairs = planRepairs({ detection, lifecycle, sandbox });
  const framework = detection.framework?.framework || "node-other";
  const dir = "akeso";

  /* Match the project's own file shape. An existing handler is replaced in
     place with its own extension, so the app's router keeps finding it. */
  const existingHandler = detection.webhookHandlers?.[0]?.file || null;
  const handlerExtension = existingHandler?.match(/\.(ts|tsx|js|mjs|jsx)$/)?.[1]
    || (ts(detection) ? "ts" : "mjs");
  const moduleExtension = ts(detection) ? "ts" : (framework === "express" ? "js" : "mjs");

  const handlerTarget = existingHandler
    || (framework === "next-app-router" ? `app/api/stripe/webhook/route.${handlerExtension}`
      : framework === "next-pages" ? `pages/api/stripe/webhook.${handlerExtension}`
      : `akeso/webhook.${moduleExtension}`);

  const entitlementPath = path.join(dir, `entitlement.${moduleExtension}`);

  /* How one generated file imports another.
     "@/akeso/entitlement" only resolves in a project that configured that
     alias; everywhere else it must be a relative path computed from the
     IMPORTING file's own directory. Deriving one specifier and reusing it
     everywhere worked only while two files happened to sit at the same depth. */
  const alias = detection.framework?.pathAlias;
  const importFrom = (fromFile, moduleName) => {
    if (alias) return `${alias}akeso/${moduleName}`;
    const target = path.join(dir, `${moduleName}.${moduleExtension}`);
    const relative = path.relative(path.dirname(fromFile), target).replace(/\\/g, "/");
    const specifier = relative.startsWith(".") ? relative : `./${relative}`;
    /* Node's ESM resolver needs the real extension; TypeScript wants it gone. */
    return ts(detection) ? specifier.replace(/\.ts$/, "") : specifier;
  };
  const entitlementImport = importFrom(handlerTarget, "entitlement");

  const files = [
    { path: entitlementPath, contents: entitlementModule(detection), why: "the one place that touches your database" },
    { path: handlerTarget, contents: webhookHandler(detection, entitlementImport), why: "the corrected Stripe webhook handler", replaces: Boolean(existingHandler) },
    { path: path.join(dir, `reconcile.${moduleExtension}`), contents: reconcileJob(detection), why: "the nightly backstop for events that never arrived" },
    { path: path.join(dir, "migration.sql"), contents: migrationSql(detection), why: "the tables the repair needs (you paste this yourself)", manual: true },
  ];

  /* The monitoring endpoints are opt-in, because they are the only way Akeso
     can ever read or write this app and a founder who only wanted the repair
     should not silently get a write path too. */
  if (withEndpoints) {
    const endpoints = akesoEndpoints(detection, importFrom);
    const routeDir = endpoints.nextish ? "app/api/akeso" : "akeso";
    const routeFile = (name) => (endpoints.nextish
      ? path.join(routeDir, name, `route.${handlerExtension}`)
      : path.join(routeDir, `${name}.${moduleExtension}`));

    files.push(
      { path: path.join(dir, `verify.${moduleExtension}`), contents: endpoints.verifier, why: "checks that a request really came from your own Akeso run" },
      { path: routeFile("restore"), contents: endpoints.restore, why: "the ONLY way Akeso can change anything here (delete it and it cannot)" },
      { path: routeFile("entitlements"), contents: endpoints.entitlements, why: "lets the monitor read your app's own answer for every account" },
    );
  }

  return { repairs, files, framework, entitlementImport, withEndpoints };
}

/* -------------------------------------------------------------- applying */

const sha = (text) => createHash("sha256").update(text).digest("hex").slice(0, 16);

export async function gitState(root) {
  const { execFile } = await import("node:child_process");
  const run = (args) => new Promise((resolve) => {
    execFile("git", ["-C", root, ...args], { timeout: 5000 }, (error, stdout) => resolve(error ? null : stdout.trim()));
  });
  if ((await run(["rev-parse", "--is-inside-work-tree"])) !== "true") return { repo: false, clean: null, dirtyFiles: [] };
  const status = await run(["status", "--porcelain"]);
  const dirtyFiles = (status || "").split("\n").filter(Boolean).map((line) => line.slice(3));
  return { repo: true, clean: dirtyFiles.length === 0, dirtyFiles };
}

/* Writes the plan, all of it or none of it.
 *
 * Everything is read and backed up BEFORE the first byte is written, so a
 * failure halfway through cannot leave an app with a new webhook handler and
 * no entitlement module — which is a worse app than the broken one it
 * replaced. If any write fails, everything already written is rolled back
 * from the copies held in memory. */
export async function applyFixPlan(root, plan, { stamp = new Date().toISOString().replace(/[:.]/g, "-") } = {}) {
  const backupDir = path.join(BACKUP_ROOT, stamp);

  /* Phase 1: read every current file and write every backup. Nothing in the
     app has changed yet. */
  const staged = [];
  for (const file of plan.files) {
    const target = path.join(root, file.path);
    const existing = await readFile(target, "utf8").catch(() => null);
    if (existing !== null && !file.manual) {
      const backupTarget = path.join(root, backupDir, file.path);
      await mkdir(path.dirname(backupTarget), { recursive: true });
      await copyFile(target, backupTarget);
    }
    staged.push({ file, target, existing });
  }

  /* Phase 2: write. On any failure, put back everything already written. */
  const written = [];
  try {
    for (const { file, target, existing } of staged) {
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, file.contents);
      written.push({
        path: file.path,
        /* What happened to the file, always — a separate "written" category
           for manual files left revert unable to undo them, and reporting the
           reason as "no backup exists" when the truth was "this file is new". */
        action: existing === null ? "created" : "replaced",
        ...(file.manual ? { manual: true } : {}),
        before: existing === null ? null : sha(existing),
        after: sha(file.contents),
      });
    }
  } catch (error) {
    for (const done of written) {
      const stagedFile = staged.find((row) => row.file.path === done.path);
      if (stagedFile.existing === null) await rm(stagedFile.target, { force: true });
      else await writeFile(stagedFile.target, stagedFile.existing);
    }
    throw new Error(`the repair was rolled back: ${error.message}`);
  }

  return { backupDir, written };
}

/* Puts the repair on its own git branch, so the founder's current branch is
   never the thing being experimented on. Best-effort: a project without git
   still gets the backup-and-revert path, which is why this never throws. */
export async function branchForFix(root, name) {
  const { execFile } = await import("node:child_process");
  const run = (args) => new Promise((resolve) => {
    execFile("git", ["-C", root, ...args], { timeout: 5000 }, (error, stdout) => resolve(error ? null : stdout.trim()));
  });
  if ((await run(["rev-parse", "--is-inside-work-tree"])) !== "true") return { branched: false, reason: "not a git repository" };
  const from = await run(["rev-parse", "--abbrev-ref", "HEAD"]);
  const created = await run(["checkout", "-b", name]);
  if (created === null) return { branched: false, reason: `could not create branch ${name}`, from };
  return { branched: true, branch: name, from };
}

/* Puts it back. Refuses any file that no longer carries the marker: that means
   a human edited it after the fix, and their work outranks the revert. */
export async function revertFix(root, fixRecord) {
  const restored = [];
  const refused = [];

  for (const file of fixRecord.files || []) {
    const target = path.join(root, file.path);
    const current = await readFile(target, "utf8").catch(() => null);
    if (current !== null && !current.includes(AKESO_MARKER)) {
      refused.push({ path: file.path, reason: "the file was edited after the fix, so it was left alone" });
      continue;
    }
    const backup = path.join(root, fixRecord.backupDir, file.path);
    const saved = await readFile(backup, "utf8").catch(() => null);
    if (saved === null) {
      if (file.action === "created" && current !== null) {
        await rm(target, { force: true });
        restored.push({ path: file.path, action: "removed" });
      } else {
        refused.push({ path: file.path, reason: "no backup exists for this file" });
      }
      continue;
    }
    await writeFile(target, saved);
    restored.push({ path: file.path, action: "restored" });
  }

  return { restored, refused };
}
