import { createHash, createHmac, timingSafeEqual } from "node:crypto";

/* The write path: how Akeso changes entitlement inside a customer's app.
 *
 * Everything else in this product tells you something. This is the one module
 * that changes something, which makes it the most dangerous file here.
 *
 * Akeso never connects to the customer's database. It calls one endpoint their
 * own app exposes (generated by `akeso-check fix`), which wraps their own
 * restore function. That endpoint is the complete list of what Akeso can do to
 * their app, it lives in their repo, and they can read it before installing it.
 *
 * Four rules shape every line below. Each one is a way this kind of code
 * normally goes wrong:
 *
 *   1. We do not take the app's word for success. "Applied" is accepted only
 *      when the app also re-read the account and the value it read back is the
 *      value we asked for. Anything less is a failure, never a pass.
 *   2. Our failure is never their verdict. A timeout, a dead server or an
 *      unreadable answer is "could_not_reach". It says the outcome is UNKNOWN.
 *      It never says "nothing happened", because we did not see that.
 *   3. A dry run that reports a change is an alarm, not a result.
 *   4. The secret signs; it never travels and it never appears in output. Every
 *      string leaving this module is swept for it one last time, because
 *      "supposed to" is how secrets end up in log files.
 */

export const RESTORE_PROTOCOL = "1";
export const DEFAULT_TOLERANCE_SECONDS = 300;
export const DEFAULT_TIMEOUT_MS = 10000;

/* The only answers an app is allowed to give. Anything else is not a verdict
   we can act on, and pretending otherwise would invent one. */
const APP_RESULTS = new Set(["applied", "no_op", "conflict", "unsupported", "failed"]);

/* Said the same way every time, because a founder reading two different
   phrasings for the same situation will think they are two situations. */
const UNKNOWN = "The outcome is unknown. The change may or may not have happened, so read this account before trying again.";
const NOTHING_SENT = "Nothing was sent to your app, so nothing was changed.";

/* -------------------------------------------------------------- signing */

/* The same scheme as the lifecycle deliveries in src/stripe-events.mjs:
   HMAC-SHA256 over "<timestamp>.<body>", with the secret used VERBATIM as the
   key. One signing story in this product, not two, because the second one is
   always the one nobody reviews. */
export function signRequest(bodyString, secret, timestamp = Math.floor(Date.now() / 1000)) {
  if (!secret) throw new Error("a restore request cannot be signed without a restore secret");
  const signature = createHmac("sha256", secret).update(`${timestamp}.${bodyString}`).digest("hex");
  return `t=${timestamp},v1=${signature}`;
}

/* timingSafeEqual throws when the two buffers differ in length, and a signature
   check that crashes is a signature check that some caller will wrap in a
   try/catch and turn into a pass. Length is compared first, in the open, and
   only equal-length values reach the constant-time compare. */
function equalConstantTime(left, right) {
  const a = Buffer.from(String(left), "utf8");
  const b = Buffer.from(String(right), "utf8");
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

/* The other half of the handshake: this is what the endpoint in the customer's
   app runs to decide whether a request really came from Akeso. Exported so
   there is one implementation of the check rather than a second one written
   from the docs. */
export function verifyRequest(bodyString, header, secret, { toleranceSeconds = DEFAULT_TOLERANCE_SECONDS, now = Date.now() } = {}) {
  if (!secret) return { valid: false, reason: "no restore secret is configured on this side" };
  if (typeof header !== "string" || header.trim() === "") return { valid: false, reason: "no signature was sent with the request" };

  const fields = {};
  for (const part of header.split(",")) {
    const match = /^\s*([a-z0-9_]+)\s*=\s*(.*?)\s*$/i.exec(part);
    if (match) fields[match[1]] = match[2];
  }
  if (!fields.t || !fields.v1) return { valid: false, reason: "the signature is not in the form Akeso sends" };
  const timestamp = Number(fields.t);
  if (!Number.isFinite(timestamp)) return { valid: false, reason: "the signature carries no readable timestamp" };

  /* Signed against the timestamp exactly as it arrived, not against the number
     it parses to: "0300" and "300" are different bytes and must not both
     verify against one signature. */
  const expected = signRequest(bodyString, secret, fields.t);
  if (!equalConstantTime(fields.v1, expected.slice(expected.indexOf("v1=") + 3))) {
    return { valid: false, reason: "the signature does not match the request body" };
  }

  /* Freshness is checked AFTER the signature on purpose. The timestamp is
     covered by the signature, so a request that is correctly signed and too old
     is not a mistake or clock drift in the header: it is the same request
     being played a second time. */
  const ageSeconds = Math.abs(Math.floor(now / 1000) - timestamp);
  if (ageSeconds > toleranceSeconds) {
    return { valid: false, reason: `the request is ${ageSeconds} seconds old, outside the ${toleranceSeconds} second window, so it is treated as a replay` };
  }

  return { valid: true, reason: "signed with the shared restore secret and inside the replay window" };
}

/* --------------------------------------------------------------- the ask */

/* The request body, built in one place so a planned restore and a sent restore
   can never disagree about what was asked for. */
function requestBody({ account, direction, target, expected, reasonCode, idempotencyKey, ruleVersion, windowKey, dryRun }) {
  return {
    akesoProtocol: RESTORE_PROTOCOL,
    account: String(account),
    direction,
    target,
    /* null means "do not check": the app applies the change whatever it reads.
       A boolean means "only if it still reads like this", which is what turns a
       lost race into a loud conflict instead of a silent overwrite. */
    expected: expected === undefined ? null : expected,
    reasonCode,
    idempotencyKey,
    ruleVersion: String(ruleVersion),
    ...(windowKey === undefined || windowKey === null ? {} : { windowKey: String(windowKey) }),
    dryRun: Boolean(dryRun),
  };
}

/* What we are about to ask for, decided before anything is sent.
 *
 * The idempotency key is derived, never random, so the same decision retried
 * inside the same window is the same key and the app can refuse the second
 * copy. A genuinely new decision carries a new windowKey and therefore a new
 * key. Remote idempotency records expire (Stripe's are kept for 24 hours), so
 * nothing here relies on the far side remembering: the ledger is the durable
 * record of what we asked for and what came back. */
export function planRestore({ account, direction, expectedState = null, ruleVersion = "1", windowKey, reasonCode = "restore:unspecified", dryRun = false } = {}) {
  if (!account) throw new Error("a restore needs the account it is about");
  if (direction !== "grant" && direction !== "remove") {
    throw new Error(`a restore direction must be "grant" or "remove", not ${JSON.stringify(direction ?? null)}`);
  }
  /* Refusing here rather than defaulting: a made-up window either welds every
     future retry to one key forever, or gives every retry a fresh key and
     defeats the whole point. Both are wrong, and neither is ours to guess. */
  if (!windowKey) throw new Error("a restore needs a windowKey, the label for the decision this key belongs to (an ISO date, a sweep id, an event id)");

  const fingerprint = createHash("sha256")
    /* JSON, not a joined string: it keeps ("a", "b") and ("a\nb", "") from
       fingerprinting to the same key. */
    .update(JSON.stringify([String(account), direction, String(ruleVersion), String(windowKey)]))
    .digest("hex")
    .slice(0, 16);

  return requestBody({
    account,
    direction,
    target: direction === "grant",
    expected: expectedState,
    reasonCode,
    idempotencyKey: `akeso-${direction}-${fingerprint}`,
    ruleVersion,
    windowKey,
    dryRun,
  });
}

/* ------------------------------------------------------------ the answer */

const stateWord = (value) => (value === true ? "access" : value === false ? "no access" : "an unknown state");

/* An unreported state is unknown, never false. Reading a missing field as
   "no access" is how a restore convinces itself it removed access it never
   touched. */
function entitledFrom(value) {
  if (typeof value === "boolean") return value;
  if (value && typeof value === "object") {
    if (typeof value.billingEntitled === "boolean") return value.billingEntitled;
    if (typeof value.entitled === "boolean") return value.entitled;
  }
  return null;
}

/* Belt and braces. No line above puts the secret into a message, but this is
   the last place we can be sure of that, so every string on the way out is
   swept once more. */
function scrubbed(outcome, secret) {
  const key = secret ? String(secret) : "";
  return JSON.parse(JSON.stringify(outcome, (_field, value) =>
    (key && typeof value === "string" && value.includes(key) ? value.split(key).join("[redacted]") : value)));
}

/* -------------------------------------------------------------- the send */

/* One POST, with a deadline we enforce ourselves rather than trusting the
   caller's fetch to have one. A restore that hangs forever holds up a sweep,
   and a sweep that never finishes is a monitor that stopped monitoring. */
async function postSigned(endpoint, init, fetchImpl, timeoutMs) {
  const controller = new AbortController();
  let fail;
  const deadline = new Promise((_resolve, reject) => { fail = reject; });
  const timer = setTimeout(() => {
    controller.abort();
    fail(new Error(`your app did not answer within ${timeoutMs}ms`));
  }, timeoutMs);

  const attempt = Promise.resolve().then(() => fetchImpl(endpoint, { ...init, signal: controller.signal }));
  /* The losing side of the race still settles. Without this, a fetch that
     rejects after the deadline already fired becomes an unhandled rejection
     and can take the whole process down. */
  attempt.catch(() => {});

  try {
    return await Promise.race([attempt, deadline]);
  } finally {
    clearTimeout(timer);
  }
}

async function readBody(response) {
  if (response && typeof response.text === "function") return response.text();
  if (response && typeof response.json === "function") return JSON.stringify(await response.json());
  throw new Error("your app's answer could not be read");
}

/* The one call that changes anything. It never throws: a caller in the middle
   of a sweep needs an outcome for the ledger, not an exception that skips the
   record of what we just attempted. */
export async function restoreEntitlement({
  endpoint,
  secret,
  account,
  target,
  expectedState,
  expected,
  direction,
  reasonCode = "restore:unspecified",
  idempotencyKey,
  ruleVersion = "1",
  windowKey,
  dryRun = false,
  fetchImpl = globalThis.fetch,
  timeoutMs = DEFAULT_TIMEOUT_MS,
} = {}) {
  const resolvedTarget = typeof target === "boolean"
    ? target
    : (direction === "grant" ? true : direction === "remove" ? false : null);
  const resolvedDirection = direction || (resolvedTarget === true ? "grant" : resolvedTarget === false ? "remove" : null);

  const base = {
    account: account === undefined || account === null ? null : String(account),
    direction: resolvedDirection,
    target: resolvedTarget,
    dryRun: Boolean(dryRun),
    reasonCode,
    idempotencyKey: idempotencyKey || null,
    before: null,
    after: null,
    beforeEntitled: null,
    afterEntitled: null,
    wouldChange: null,
    verified: false,
    httpStatus: null,
    /* The difference between "we know nothing changed" and "we do not know".
       Collapsing the two is the single most dangerous thing this module could
       do, so it is a field and not a turn of phrase. */
    outcomeKnown: true,
  };
  const finish = (fields) => scrubbed({ ...base, ...fields }, secret);
  const refuse = (reason) => finish({ result: "could_not_reach", reason: `${reason} ${NOTHING_SENT}` });

  /* Nothing left this process for any of these, so "nothing changed" is a
     measurement here, not an assumption. */
  if (!endpoint) return refuse("Akeso has no restore endpoint for this app.");
  if (!secret) return refuse("Akeso has no restore secret for this app.");
  if (typeof fetchImpl !== "function") return refuse("This Node build has no fetch available.");
  if (!base.account) return refuse("No account was given.");
  if (resolvedTarget === null) return refuse("No target state was given, and Akeso will not guess which way to move an account.");
  if (!base.idempotencyKey) return refuse("No idempotency key was given, and a write without one turns a retry into a second write.");

  const body = requestBody({
    account: base.account,
    direction: resolvedDirection,
    target: resolvedTarget,
    expected: expectedState !== undefined ? expectedState : (expected !== undefined ? expected : null),
    reasonCode,
    idempotencyKey: base.idempotencyKey,
    ruleVersion,
    windowKey,
    dryRun,
  });
  const bodyString = JSON.stringify(body);

  let response;
  try {
    response = await postSigned(endpoint, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        /* The signature travels. The secret does not, ever. */
        "akeso-signature": signRequest(bodyString, secret),
        "idempotency-key": base.idempotencyKey,
        "user-agent": "akeso-check",
      },
      body: bodyString,
    }, fetchImpl, timeoutMs);
  } catch (error) {
    /* Ours, not theirs. The request may have arrived and been applied before
       the connection died, so this reports an unknown outcome and never a
       verdict about the app. */
    return finish({
      result: "could_not_reach",
      outcomeKnown: false,
      reason: `Akeso could not complete the call to your app: ${error?.message || String(error)}. ${UNKNOWN}`,
    });
  }

  const httpStatus = typeof response?.status === "number" ? response.status : null;

  let text;
  try {
    text = await readBody(response);
  } catch (error) {
    return finish({
      result: "could_not_reach",
      outcomeKnown: false,
      httpStatus,
      reason: `Your app answered${httpStatus === null ? "" : ` ${httpStatus}`} but the answer could not be read: ${error?.message || String(error)}. ${UNKNOWN}`,
    });
  }

  let answer = null;
  try {
    answer = JSON.parse(text);
  } catch {
    answer = null;
  }
  if (!answer || typeof answer !== "object" || Array.isArray(answer)) {
    return finish({
      result: "could_not_reach",
      outcomeKnown: false,
      httpStatus,
      reason: `Your app answered${httpStatus === null ? "" : ` ${httpStatus}`} with something that is not the JSON Akeso expects. ${UNKNOWN}`,
    });
  }

  const claimed = typeof answer.result === "string" ? answer.result : "";
  const appReason = typeof answer.reason === "string" && answer.reason.trim() ? answer.reason.trim() : null;
  const before = answer.before ?? null;
  const after = answer.after ?? null;
  const beforeEntitled = entitledFrom(before);
  const afterEntitled = entitledFrom(after);
  const wouldChange = typeof answer.wouldChange === "boolean"
    ? answer.wouldChange
    : (beforeEntitled === null ? null : beforeEntitled !== resolvedTarget);
  const seen = { httpStatus, before, after, beforeEntitled, afterEntitled, wouldChange };

  if (!APP_RESULTS.has(claimed)) {
    return finish({
      ...seen,
      result: "could_not_reach",
      outcomeKnown: false,
      reason: `Your app answered${httpStatus === null ? "" : ` ${httpStatus}`} but did not say what it did${claimed ? ` (it said "${claimed}")` : ""}. ${UNKNOWN}`,
    });
  }

  /* Rule 3. A dry run is a question, and an app that answers a question by
     doing the thing has a bug we cannot see the extent of. This is deliberately
     the loudest branch in the file. */
  if (dryRun && claimed === "applied") {
    return finish({
      ...seen,
      result: "failed",
      outcomeKnown: false,
      reason: `Your app was asked for a dry run and reported that it applied the change. A dry run must change nothing, so your restore endpoint is not honouring dryRun. Stop using --apply against this app and read this account now, because it may really have been changed.`,
    });
  }
  if (dryRun && beforeEntitled !== null && afterEntitled !== null && beforeEntitled !== afterEntitled) {
    return finish({
      ...seen,
      result: "failed",
      outcomeKnown: false,
      reason: `Your app was asked for a dry run and reported the account in one state before and a different one after. A dry run must change nothing. Read this account now, and do not run this again with --apply until your restore endpoint is fixed.`,
    });
  }

  if (claimed === "applied") {
    /* Rule 1, in three parts. An app is allowed to be wrong about itself; it is
       not allowed to be believed about itself. */
    if (answer.verified !== true) {
      return finish({
        ...seen,
        result: "failed",
        outcomeKnown: false,
        reason: `Your app said it changed this account but did not confirm it by reading the account back${appReason ? `. It also said: ${appReason}` : ""}. Akeso does not record a change it cannot see confirmed. ${UNKNOWN}`,
      });
    }
    if (afterEntitled === null) {
      return finish({
        ...seen,
        result: "failed",
        outcomeKnown: false,
        reason: `Your app said it changed this account and confirmed it, but did not report what the account reads as now, so there is nothing to check the claim against. ${UNKNOWN}`,
      });
    }
    if (afterEntitled !== resolvedTarget) {
      return finish({
        ...seen,
        result: "failed",
        outcomeKnown: false,
        reason: `Akeso asked for ${stateWord(resolvedTarget)} and your app reported ${stateWord(afterEntitled)} afterwards, so the change did not land the way it was asked for. ${UNKNOWN}`,
      });
    }
    return finish({
      ...seen,
      result: "applied",
      verified: true,
      reason: `Your app changed this account to ${stateWord(resolvedTarget)} and read it back to confirm.`,
    });
  }

  if (claimed === "no_op") {
    const state = afterEntitled === null ? beforeEntitled : afterEntitled;
    /* A dry run legitimately reports a state that differs from the target: that
       is the preview, not a contradiction. Only a real run gets checked here. */
    if (!dryRun && state !== null && state !== resolvedTarget) {
      return finish({
        ...seen,
        result: "failed",
        outcomeKnown: false,
        reason: `Your app said nothing needed changing, but reported the account as ${stateWord(state)} when Akeso asked for ${stateWord(resolvedTarget)}. Those cannot both be true. ${UNKNOWN}`,
      });
    }
    if (state === null) {
      /* Rule 3 of the doctrine: unprovable is never a pass. The result stands,
         but nothing here is marked confirmed. */
      return finish({
        ...seen,
        result: "no_op",
        reason: `Your app said nothing needed changing but did not report the account's state, so this was not confirmed. Read the account yourself before relying on it.`,
      });
    }
    return finish({
      ...seen,
      result: "no_op",
      verified: !dryRun && state === resolvedTarget,
      reason: dryRun
        ? `Nothing was changed. This was a dry run.`
        : `Nothing needed changing. Your app already had this account at ${stateWord(resolvedTarget)}.`,
    });
  }

  if (claimed === "conflict") {
    return finish({
      ...seen,
      result: "conflict",
      reason: `The account changed between Akeso reading it and Akeso writing to it, so your app refused and nothing was changed${appReason ? `. Your app said: ${appReason}` : ""}.`,
    });
  }

  if (claimed === "unsupported") {
    return finish({
      ...seen,
      result: "unsupported",
      reason: `Your app refused to change this account on purpose${appReason ? `: ${appReason}` : ""}. Nothing was changed.`,
    });
  }

  return finish({
    ...seen,
    result: "failed",
    /* The app said so itself, and an app that reports its own failure is an app
       that got far enough to know. */
    reason: `Your app tried and could not change this account${appReason ? `: ${appReason}` : ""}. Nothing was confirmed.`,
  });
}

/* ------------------------------------------------------------- receipts */

/* One line a founder can read without help: what we saw, what changed, and
   whether anyone checked afterwards. Every line ends with what happens next,
   because a receipt that leaves someone wondering is a support ticket. */
export function describeOutcome(outcome) {
  if (!outcome || typeof outcome !== "object") return "No outcome was recorded, so nothing can be said about this account.";

  const who = `Account ${outcome.account ?? "unknown"}`;
  const wanted = stateWord(outcome.target);
  const saw = stateWord(outcome.beforeEntitled);
  const reason = outcome.reason ? String(outcome.reason) : "";

  if (outcome.result === "could_not_reach") {
    return outcome.outcomeKnown
      ? `${who}: nothing was sent to your app, so nothing changed. ${reason}`
      : `${who}: Akeso could not get a usable answer from your app. The change may or may not have happened. Read this account before trying again.`;
  }

  if (outcome.dryRun) {
    if (outcome.result === "failed") return `${who}: DRY RUN PROBLEM. ${reason}`;
    if (outcome.result === "unsupported") return `${who}: dry run only, nothing was changed. On a real run your app would refuse this one. ${reason}`;
    if (outcome.result === "conflict") return `${who}: dry run only, nothing was changed. Your app reports the account has moved since Akeso read it, so it would refuse a real run too.`;
    if (outcome.wouldChange === true) return `${who}: dry run only, nothing was changed. Akeso saw ${saw}, and a real run would set it to ${wanted}.`;
    if (outcome.wouldChange === false) return `${who}: dry run only, nothing was changed. Your app already has this account at ${wanted}, so a real run would change nothing.`;
    return `${who}: dry run only, nothing was changed. Your app did not report the account's state, so Akeso cannot say what a real run would do.`;
  }

  if (outcome.result === "applied") {
    return `${who}: Akeso saw ${saw}, your app set it to ${wanted}, and it was confirmed by reading the account back afterwards. Nothing more to do.`;
  }
  if (outcome.result === "no_op") {
    return outcome.verified
      ? `${who}: already at ${wanted}, so nothing was changed. Confirmed by reading the account.`
      : `${who}: your app said nothing needed changing, but it was not confirmed. Read the account yourself before relying on it.`;
  }
  if (outcome.result === "conflict") {
    return `${who}: nothing was changed, because the account moved between Akeso reading it and writing to it. Akeso will see it again on the next sweep.`;
  }
  if (outcome.result === "unsupported") {
    return `${who}: your app refused this one on purpose, so nothing was changed. ${reason} That refusal is your app's own rule, so change it there if it is wrong.`;
  }
  return `${who}: Akeso asked for ${wanted} and it was not confirmed. ${reason} Read this account before trying again.`;
}

/* ------------------------------------------------------- into the ledger */

/* The outcome, shaped for src/ledger.mjs. Append it with appendEntry; nothing
   here writes to disk, so there is exactly one persistence path in the product.
 *
 * It carries `outcomeKnown` and `dryRun` on purpose. A "could_not_reach" read
 * back next month without them looks like "nothing happened", which is the one
 * thing it does not mean. */
export function restoreLedgerEntry(outcome) {
  return {
    kind: "restore",
    account: outcome.account,
    direction: outcome.direction,
    reasonCode: outcome.reasonCode,
    idempotencyKey: outcome.idempotencyKey,
    result: outcome.result,
    before: outcome.beforeEntitled,
    after: outcome.afterEntitled,
    verified: Boolean(outcome.verified),
    outcomeKnown: outcome.outcomeKnown !== false,
    dryRun: Boolean(outcome.dryRun),
    reason: outcome.reason ?? null,
    httpStatus: outcome.httpStatus ?? null,
  };
}

/* The adapter runSweep expects: restore(account, target, { expected, reasonCode,
   idempotencyKey }). Everything about WHERE to write and HOW to sign is bound
   once, here, so the sweep never handles the secret at all. */
export function restoreVia({ endpoint, secret, ruleVersion = "1", dryRun = false, fetchImpl, timeoutMs = DEFAULT_TIMEOUT_MS }) {
  return (account, target, { expected = null, reasonCode = "restore:unspecified", idempotencyKey, windowKey } = {}) =>
    restoreEntitlement({
      endpoint, secret, account, target, expectedState: expected,
      reasonCode, idempotencyKey, ruleVersion, windowKey, dryRun, fetchImpl, timeoutMs,
    });
}
